# Generated by Django 3.1.6 on 2021-02-04 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='when',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='چه موقع'),
        ),
    ]
