# Generated by Django 3.1.6 on 2021-02-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210204_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='لینک پروژه'),
        ),
    ]
