# Generated by Django 3.1.6 on 2021-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_experience_how'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='forWho',
            field=models.CharField(blank=True, max_length=300, verbose_name='برای چه کسی پروژه را انجام دادید'),
        ),
    ]
