# Generated by Django 3.1.6 on 2021-02-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210204_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo', verbose_name='لوگو'),
        ),
    ]
